### ISSUE TITLE
No Proper File Management

### ISSUE THREAD

**Issue by NaviRocker** [scorelab/DroneSym#101]
CONTRIBUTING.md, ISSUE_TEMPLATE.md, and PULL_REQUEST_TEMPLATE.md are separately located in the Home. It is recommended to add those three into a separate folder named .github for easy use of Github.

So It's better to follow what Github recommend.

**Comment by ivantha** [comment]
@dilinade Can you work on this please?

**Comment by dilinade** [comment]
@ivantha Sure, I will look on to this!

**Comment by dilinade** [comment]
@ivantha Moved files and made a PR. Please review.
