### ISSUE TITLE
Drone Name

### ISSUE THREAD

**Issue by Manish-Varrier** [scorelab/DroneSym#105]
In the current version, we are not able to assign a name to the drone. The user should be given the ability to name his/her drone. This is a feature that everyone wishes for. 

Also, it would be good if the files were arranged more properly as some of them are scrambled.

**Comment by dilinade** [comment]
I'm working on this!

**Comment by ivantha** [comment]
@dilinade This is similar to #84. You can probably implement those features as well.

**Comment by dilinade** [comment]
@ivantha Sure thing. Will look on to it.

**Comment by dilinade** [comment]
@ivantha This issue can be closed as well. :)
