### ISSUE TITLE
Live Voice Chat.

### ISSUE THREAD

**Issue by SanyamPunia** [scorelab/DroneSym#106]
There should be some kind of feature that enable the users to do Live Voice Chat using IVR or something.
It can be done by connecting users with themselves with some kind of special code or best option is using IP address.
This could be the big improvement for current application.

In the right top corner, there should be an option that connects the user to do live voice chat.

![dronesym](https://user-images.githubusercontent.com/35108041/47602925-c08c2580-da02-11e8-82c3-1fcab48d0a0e.PNG)

**Comment by ivantha** [comment]
This issue is reaching too far from the original purpose of DroneSym.
