### ISSUE TITLE
Travis CI doesn't run nodejs tests

### ISSUE THREAD

**Issue by jmularski** [scorelab/DroneSym#114]
Currently Travis CI tests only python code.

**Comment by jmularski** [comment]
Wanted to modify .travis.yml file to include also nodejs tests, but no idea how to jump over python server dependency, anybody from maintainers have any idea?

**Comment by dilinade** [comment]
I'm working on this issue.

**Comment by ivantha** [comment]
@dilinade Were you able to fix it?

**Comment by dilinade** [comment]
@ivantha Still trying. Seems like there's an issue putting firebase credentials plus the code to an environment variable.
I will get it done soon
