### ISSUE TITLE
Setup error and suggestion

### ISSUE THREAD

**Issue by geethmaka** [scorelab/DroneSym#116]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Cannot find module error

# Current Behavior

What is the current behavior?
npm start is not working

![screenshot 60](https://user-images.githubusercontent.com/41124555/47939255-a4a9e780-df0c-11e8-9139-b2f504acc7f0.png)

[SUGGESTION]
Add how to use these in windows platforms because everyone cant deal with linux and add some more info for the installation part and heres the most important thing ** please add the common errors can occur during installation and running and how to get over that error according to the experience of the main developers.

**Comment by ivantha** [comment]
You have to add the Firebase credential file to the dronesym-node folder before running 🙂 
It is the step 3 of **Setting up the Node environment* part. But I see that why you may have missed it. You are welcome to do a PR to clearly mention it in the README.md.
