### ISSUE TITLE
[Error] Throwing error related to MongoDB

### ISSUE THREAD

**Issue by Kalyan3578** [scorelab/DroneSym#126]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

The command `mongorestore --db dronesym dronedb/dronesym` was expected to run. I did install mongodb in a proper way before starting the process. Before this, the Firebase admin steps were also correctly done. But the terminal is still throwing an error. 

# Current Behavior

![16](https://user-images.githubusercontent.com/34546340/48046079-f5de0380-e1b8-11e8-8ec7-e1b9f4de02ac.PNG)

The following error is blocking the process. I tried many minor fixes such as updating to the latest/stable versions, re-installing dependencies etc. Nothing worked. The Firebase file and credentials are well set up for the process to be working. 

## Context

The problem is with mongodb. 
I installed mongodb following this tutorial: [https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/](url)

I followed everything right and mongodb is indeed installed in my Ubuntu but doesn't work or respond. 
So I thought of installing mongodb again using the way sudo suggests. But I end up getting this error:

```sudo apt install mongodb-clients
[sudo] password for kalyan:
Reading package lists... Done
Building dependency tree      
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mongodb-org : Conflicts: mongodb-clients but 1:2.6.10-0ubuntu1 is to be installed
 mongodb-org-mongos : Conflicts: mongodb-clients but 1:2.6.10-0ubuntu1 is to be installed
 mongodb-org-server : Conflicts: mongodb-clients but 1:2.6.10-0ubuntu1 is to be installed
 mongodb-org-shell : Conflicts: mongodb-clients but 1:2.6.10-0ubuntu1 is to be installed
 mongodb-org-tools : Conflicts: mongodb-clients but 1:2.6.10-0ubuntu1 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.```

Is there any possible fix for this so I can get past this error and move on to the python part?

**Comment by angeryrohan** [comment]
Hey @Kalyan3578 Please refer #142 , I've given the fix for this, The instruction isn't actually listed in the README.MD..
Thanks ^.^
