### ISSUE TITLE
Make it Python 3 compatible

### ISSUE THREAD

**Issue by dilxhan** [scorelab/DroneSym#128]
# Prerequisites

- [✔ ] I am running the latest version
- [✔ ] I checked the documentation and found no answer
- [✔ ] I checked to make sure that this issue has not already been filed
- [✔ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Process to run successfully.

# Current Behavior

The source isn't Python 3 compatible

**Comment by dilinade** [comment]
I'm working on this.
