### ISSUE TITLE
No Forgot Password option

### ISSUE THREAD

**Issue by emgaurv** [scorelab/DroneSym#131]
# Expected Behavior

There should be a button on Login Page which send password reset email to the respective user which redirects to password reset form.

# Current Behavior

There's no such feature available.

**Comment by meetcric** [comment]
I would like to work on this issue..@ivantha

**Comment by meetcric** [comment]
To implement "forget-password" feature I need an email-id from which we sent a new password to the user. 
so can you give me email-id or for now i will use mine?@ivantha

**Comment by Anmolbansal1** [comment]
@meetcric are you still working on this??

**Comment by meetcric** [comment]
Yes @Anmolbansal1

**Comment by meetcric** [comment]
@ivantha I think it is a stale issue, should we close it or I make a PR for this?

**Comment by ivantha** [comment]
@meetcric Did you implement the functionality?

**Comment by meetcric** [comment]
@ivantha actually I am on the halfway, will be completed within next 2 days. should I drop it?

**Comment by ivantha** [comment]
@meetcric It would be better if you could complete it 🙂
