### ISSUE TITLE
[Dronesym-node]Failed: Error connecting to db server: no reachable servers

### ISSUE THREAD

**Issue by hohieu01** [scorelab/DroneSym#142]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
Import the database with `mongorestore --db dronesym dronedb/dronesym`

# Current Behavior

What is the current behavior?
`Failed: Error connecting to db server: no reachable servers`
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.
In part 1, Part 1 - Setting up the Node environment, READ.ME should add monodb in Prerequisites
Before Import the database with `mongorestore --db dronesym dronedb/dronesym` should add `sudo apt install mongo-tools`
However, after installing mongo-tools, I run `mongorestore --db dronesym dronedb/dronesym` and get some error
![image](https://user-images.githubusercontent.com/23649434/48663330-2f6c1400-eac1-11e8-8685-e5ce843d88de.png)
Error `Failed: Error connecting to db server: no reachable servers`
## Context
`hoduchieu01@hoduchieu01:~/DroneSym/dronesym-node$ npm install
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
hoduchieu01@hoduchieu01:~/DroneSym/dronesym-node$ sudo apt install mongo-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
mongo-tools is already the newest version (3.6.3-0ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 409 not upgraded.
hoduchieu01@hoduchieu01:~/DroneSym/dronesym-node$ mongorestore --db dronesym dronedb/dronesym
2018-11-17T23:42:40.065+0700	Failed: error connecting to db server: no reachable servers
hoduchieu01@hoduchieu01:~/DroneSym/dronesym-node$
`

## Failure Logs

`Failed: Error connecting to db server: no reachable servers`

**Comment by Benjamin-Mueggenburg** [comment]
Do you have the database service running? Trying running `mongod` in another terminal - and leave it running, then run `mongorestore`

**Comment by angeryrohan** [comment]
And also make sure that before running mongod in another terminal, You've made a directory for Mongo, because mongo requires a directory to store it's server.
<b> Check this by running</b> ```mongod```, <b>If you get an error with status code 100 like this:</b>

![error](https://user-images.githubusercontent.com/29266591/49378019-a7794180-f731-11e8-9013-b202aaa2f297.png)

FIX:
1.  ```mkdir -p /data/db``` - Creates the directory required by Mongo for you

2. ```sudo chown -R `id -un` /data/db``` - Check right permissions
 Done ^.^
