### ISSUE TITLE
Issues on Login Page

### ISSUE THREAD

**Issue by hohieu01** [scorelab/DroneSym#148]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
 
# Expected Behavior
Improve User experience
In Login Page, it is more convenient for user who hasn't account before if it has a SignUp button link to SignUp page.

# Current Behavior
Login Page hasn't SignUp Button.
![image](https://user-images.githubusercontent.com/23649434/48698703-5722bf80-ec1a-11e8-9c48-6bcd594bf301.png)
![image](https://user-images.githubusercontent.com/23649434/48698813-9e10b500-ec1a-11e8-8791-1291afc18c33.png)

What is the current behavior?

Login Page hasn't SignUp Button.

**Comment by hohieu01** [comment]
Login Page add capcha for checking people not computer.

**Comment by meetcric** [comment]
can I start working on this issue? @ivantha @charithccmc

**Comment by ivantha** [comment]
@meetcric Yeah. Go ahead! 🙂

**Comment by meetcric** [comment]
@ivantha Actually after going through the  workflow of "login" I am thinking we need to refactor the user login and signup workflow because in the user model "Email" field is not present which may create a problem in the process like "forget password"(where we can't send the recovery password to a user), so can i add email option while creating a new user?

**Comment by ivantha** [comment]
@meetcric "forgot password" feature would be a good addition to the project. 
So you can work on that if you prefer 👍

**Comment by meetcric** [comment]
@ivantha while creating that signup feature I have added "email" field in UserSchema. therefore the create user feature of the "Manage user" page need to be updated, so can I create a new issue regarding this upgradation and start working on this?
