### ISSUE TITLE
[UX] Active Route is not indicated

### ISSUE THREAD

**Issue by TheLukaszNs** [scorelab/DroneSym#153]
# Current Behavior
The Navbar and Sidebar (at the `dashboard/user` route) don't show which route is selected. It's not a big issue, but we can slightly improve User Experience by indicating on what page the user currently is.
<img alt="ds_routes" src="https://user-images.githubusercontent.com/25536472/49181029-98bc1480-f356-11e8-9956-f139139749cc.png" width="75%" />

# Expected Behavior
The Links in the Navbar and Sidebar should be showing in which route the user currently is.

## Steps to Reproduce
1. Login to *DroneSym*
2. Go to the *Dashboard* section (or any other)

**Comment by meetcric** [comment]
Can i Start working on this issue? @rhperera @ivantha

**Comment by ivantha** [comment]
@meetcric Yeah. Definitely 🙂

**Comment by meetcric** [comment]
@ivantha should I use Angular2 Breadcrumb for the user navigation on the website?

**Comment by meetcric** [comment]
Hey @ivantha, can u please tell me more about the expected behavior, so that I can start working on this issue?

**Comment by ivantha** [comment]
@meetcric You can use any method you want to indicate the route of the user. Maybe something like breadcrumbs etc.
