### ISSUE TITLE
Bug   Comapny logo redirects to login page

### ISSUE THREAD

**Issue by prijeshb** [scorelab/DroneSym#251]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

On clicking DroneSym Logo name user must be redirected to homepage.

# Current Behavior

It is redirected to login page instead.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. click on DroneSym after logging or signing up on dashborad

**Comment by dilinade** [comment]
I would like to work on this issue

**Comment by prijeshb** [comment]
@dilinade Alreay working on it !!

**Comment by dilinade** [comment]
@prijeshb Are you done with this?
I just saw the comment and I'm done.

**Comment by prijeshb** [comment]
I have already done it but forgot to make pull request ;(
