### ISSUE TITLE
Console should be cleared

### ISSUE THREAD

**Issue by prijeshb** [scorelab/DroneSym#267]
# Expected Behavior

There should no logs seen in console.

# Current Behavior

What is the current behavior?

Several logs are logged to console.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Clicking on active navigation route like (dashboard) 
2. Open console of browser and you get array as logged

**Comment by ivantha** [comment]
@dilinade Do we have any console logs remaining in the code?

**Comment by dilinade** [comment]
Yes, I will be clearing them up in the next PR.
