### ISSUE TITLE
Make DroneSym a Progressive Web Application (PWA)

### ISSUE THREAD

**Issue by ivantha** [scorelab/DroneSym#290]

**Comment by Rupeshiya** [comment]
@ivantha are you working on this also I need some help for setting this up?

**Comment by ivantha** [comment]
> @ivantha are you working on this also I need some help for setting this up?

@dilinade is working on these issues as a part of his Google Summer of Code 2019 Project. But there is no reason that you can't join in on it 🙂 

You can find information about how to setup DroneSym in the README. And please join the Gitter channel if you need more help (https://gitter.im/scorelab/DroneSym)
