### ISSUE TITLE
Docker install error on windows

### ISSUE THREAD

**Issue by chamiduu** [scorelab/DroneSym#440]
**Error when try to install Dronesym with docker**

When the command `docker-compose up` executed in the project root, It gives this error.

![5](https://user-images.githubusercontent.com/41909955/72128233-0e9af980-3327-11ea-810b-c2a05fa43173.PNG)

My environment - 
       

- OS - Windows 10 1903

- Docker version -  19.03.5, build 633a0ea

- Node - v13.5.0

**Comment by ivantha** [comment]
@dilinade Do you know what causes this?

**Comment by dilinade** [comment]
@cjprogamer Does _docker ps_ working fine? And is virtualization enabled in your machine?
@ivantha I think it's an issue due to a misconfig in the local environment

**Comment by JosephSemrai** [comment]
@dilinade I believe it may be a config issue. The docker build is successful for me on Windows Build 18363:
![image](https://user-images.githubusercontent.com/29003194/72215248-dccc9300-34de-11ea-8030-4417c8396bcd.png)

**Comment by dilinade** [comment]
@JosephSemrai So it builds successfully  right?

**Comment by JosephSemrai** [comment]
@dilinade Yes, it builds for me on Windows.
