### ISSUE TITLE
Repo should follow GitFlow workflow

### ISSUE THREAD

**Issue by raghavpuri** [scorelab/DroneSym#54]
This repos should follow Gitflow workflow and follow are the items you have to check. 
- [x] There is a `master` branch and a `develop` branch.
- [x] `master` branch is locked for direct commits and, 
  - [x] Require pull request reviews before merging is active
  - [x] Require status checks to pass before merging is active
    - [x] Require branches to be up to date before merging
    - [x] Appropriate Status checks are required
  - [x] Enforce all configured restrictions for administrators is active
  - [ ] Restrict only maintainers group can push to the master branch

**Comment by ivantha** [comment]
Git workflow is already enforced in this repo.
