### ISSUE TITLE
Dockers should have proper Label Schema labels

### ISSUE THREAD

**Issue by tanmayanand44** [scorelab/DroneSym#55]
This repos has a Dockerfile but it does not contain any Label Schema labels.  Following are the lables we have to have on our Dockers. 
- [ ] `name` 
- [ ] `description` Shoud be on user's perspective.
- [ ] `url` Should be SCoRe website
- [ ] `vcs-url` Should point to GitHub repo
- [ ] `vcs-ref`
- [ ] `vendor` Shoudl be "SCoRe Lab"
- [ ] `version`
- [ ] `schema-version`

**Comment by agentmilindu** [comment]
Dockers can be found in `docker` branch (  https://github.com/scorelab/DroneSym/tree/docker )

**Comment by Kalyan3578** [comment]
I'm going to work on one of the dockerfile!

**Comment by agentmilindu** [comment]
Nice! Pick one and tell us.

**Comment by Kalyan3578** [comment]
@agentmilindu I have already started working on this dockerfile: https://github.com/scorelab/DroneSym/blob/docker/dronesym-python/Dockerfile

**Comment by agentmilindu** [comment]
@tanmayanand44 Nice!
