### ISSUE TITLE
New Features for DroneSym

### ISSUE THREAD

**Issue by iammosespaulr** [scorelab/DroneSym#63]
![screenshot from 2018-01-02 12-31-37](https://user-images.githubusercontent.com/28682735/34481473-72f04a60-efc3-11e7-8e28-bfa2b54cdd62.png)
 
The Login Page Has Only The Words Login It could be Made into LOGIN TO DRONESYM or something like that

**Comment by iammosespaulr** [comment]
We need to have an improved login Page as well as a better DashBoard as the current one is not that good  We Should Have the options to choose the MAP section.
![screenshot from 2018-01-02 12-32-15](https://user-images.githubusercontent.com/28682735/34483078-5e8db12a-efcd-11e7-887f-535ef00b9c0b.png)

**Comment by malithsen** [comment]
>We Should Have the options to choose the MAP section rather than have it stay all the time.

Hi @iammosespaulr could you please elaborate this

**Comment by iammosespaulr** [comment]
@malithsen  What I wanted to say was that the map remains open all the time ,we should have some kind of toggle option for the map

**Comment by malithsen** [comment]
I think it's sensible for the main view to have the map opened by default because that's a what a user would use for the majority of the time with dronesym.

**Comment by iammosespaulr** [comment]
Yeah It makes sense but i was thinking from the perspective of a person who would like to save mobile data and computing power

**Comment by iammosespaulr** [comment]
Why not have the drone's camera connected???                <---- New feature

**Comment by iammosespaulr** [comment]
Use multiple drone cameras To stitch a huge picture using a python script and have it broadcast on the screen .. This would give you live feed of a huge area

**Comment by iammosespaulr** [comment]
Most drones these days are capable of broadcasting live video feeds and based on the drone's position we could write a script that would stitch the live feeds to help us monitor huge areas.

**Comment by iammosespaulr** [comment]
@malithsen Would you approve my GCI task ?

**Comment by malithsen** [comment]
1. While it could be useful for certain users to have stitched live feeds, I believe such a feature would be out of the scope of dronesym's intended use cases. Viewing real-time data individually on the other hand makes more sense #60 
2. Please open a new issue for new suggestions
