### ISSUE TITLE
Dynamic Flight feature

### ISSUE THREAD

**Issue by debugvelop** [scorelab/DroneSym#70]
Dynamic flight is a feature that allows drones to fly normally in unpredictable condition or adapt with the condition. Dynamic flight uses data from drone's sensors to analyze the environment around them. If there are obstacles, bad weather, birds, or anything drone will do a maneuver to avoid them. This feature also helps drone fleet to keep the formation if one drone failed.

**Comment by malithsen** [comment]
Hi @debugvelop, dronesym cannot and have not attempted to add features to drones. Please read the description and get yourself familiarized with the project
