### ISSUE TITLE
New Feature - Drone Sym 

### ISSUE THREAD

**Issue by Ashoksingar** [scorelab/DroneSym#74]
New Feature -
1) Claw - Claw specially made for drone weight and propeller. Claw can be used to pick up things and transport it. Claw should be designed as such it takes less space and can stretch to maximum length. The concept of origami can be used to design such claws.
2) GPS - GPS sensor can be used to locate the drone.
3) Compass Sensor can also be attached.
4) The frame is made of carbon fiber, which is widely used in aerospace industry for its characteristics such as:
- Physical strength, robustness, and lightweight;
- Good vibration damping;
- High dimensional stability  
- Water Proof ( Coating )

**Comment by iammosespaulr** [comment]
Hey there ...
Did you go through the dronesym project ?
quoting @malithsen 
"Hi @debugvelop, dronesym cannot and have not attempted to add features to drones. Please read the description and get yourself familiarized with the project"
