### ISSUE TITLE
New features for DroneSym

### ISSUE THREAD

**Issue by AdhyanDhull** [scorelab/DroneSym#75]
1) DroneSym should also be available on mobile phones and tablets. As in today's fast rapid world there is a need for on the go control for almost everything. Bringing DroneSym to mobile phones will widen it's reach and users can control their drone fleets on the go.

2) Also users should have the functionality to utilize their drone's features on DroneSym. Features like live camera footage, or receive live data from sensors on-board on drone should be available on web-dashboard too. There should also be an option for users to add various features of the drone (so that the DroneSym team can work on bringing accessibility to new features too) while adding a new drone.

3) Also the map on DroneSym should contain warnings or should not allow users to add flight path for no fly zones like Military Campuses or other areas where drone flying is prohibited.

**Comment by malithsen** [comment]
While your suggested features are good they are out of the scope of the problem DroneSym was built for. 
1. This would not be a feature. It would either be a new mobile app which relies on DroneSym's existing API or making the current interface more mobile friendly
2.   Suggested in #60 
3. This sounds good. Please open a new issue with a title depicting the core idea of your suggestion.

Closing this
