### ISSUE TITLE
Dual Battery System

### ISSUE THREAD

**Issue by USHARMAVN** [scorelab/DroneSym#80]
**_EXPLANATION_**
The drone should work on dual battery rechargeable system. 
The manufacturer should charge one of it's battery to the fullest. 
Now, when the user uses the drone, the second battery (empty one) should get charged due to the rotational energy of the propellor hovering above (like a turbine charging system). Hence as soon as the first battery would get discharged, the drone would not fall, but fly by using the second battery. 
Further the first battery would get charged as explained above. And this cycle goes on and on. 

**Advantages:-**
**_1. This would lead to uninterrupted completion of the task
2. this would help save a lot of energy._**

**Comment by malithsen** [comment]
Hi @USHARMAVN, dronesym cannot and have not attempted to add features to drones. Please read the description and get yourself familiarized with the project
An interesting concept though.
