### ISSUE TITLE
Thermal Imaging Sensor. 

### ISSUE THREAD

**Issue by ghost** [scorelab/DroneSym#81]
We can add the thermal sensing feature which actually displays the heat in the environment. It would display if the drone is adaptable to the environment. Also, if the drone is entering any very heated or cooled environment we could set an alarm which would alarm the user as I have seen people relaxing despite their drone is flying. This function may work at a specific range.  
**For Eg.** 
If the drone is going near a barbecue (for instance), it may show the emitted heat which would get displayed and alarm the user. This will help the user to maintain the quality, functionality, and help the drone remain safe. 
The user will as well get uninterrupted use of the drone.

**Comment by malithsen** [comment]
Hi 
While your suggestion will be useful to a drone pilot, it is out of the scope of DroneSym. DroneSym does not attempt to add features to drones, rather it is a platform enabling users to handle and track their drone fleets in real time. It relies on the messages sent from the drone itself. Heat sensors are not a common feature of a drone.
