### ISSUE TITLE
Provide pluggable option for firebase alternatives

### ISSUE THREAD

**Issue by kmehant** [scorelab/DroneSym#83]
Since DroneSym is an open source application supporting users to track their drone fleet, we have to even provide options to plug in other open source alternatives for firebase. 

**Why?** 

To support users to be able to scale and use the other best, open source and cost effective resources. No doubt, Firebase is one of the best option for realtime databases, auth etc. but it's not so scalable when coming to cost effectiveness. We should definitely come up with a solution and design a model to provide plugin options to atleast two other alternative to Firebase

**Comment by dilinade** [comment]
Now it's been migrated to MongoDB and the issue has been solved.
Addressed with #319
