### ISSUE TITLE
App. Install Issues

### ISSUE THREAD

**Issue by tymiles003** [scorelab/DroneSym#93]
Team,
I'm having issues trying to complete an install, is there a docker ir script available to complete install? Here's the error I get:

oot@enC-ODM2:/opt/DroneSym/dronesym-python/flask-api/src# python main.py
main.py:68: SyntaxWarning: name 'q' is assigned to before global declaration
  global q
('Connection aborted.', gaierror(-2, 'Name or service not known'))
Retrying...
('Connection aborted.', gaierror(-2, 'Name or service not known'))
Retrying...
('Connection aborted.', gaierror(-2, 'Name or service not known'))
Retrying...
('Connection aborted.', gaierror(-2, 'Name or service not known'))
Retrying...
^CTraceback (most recent call last):
  File "main.py", line 71, in <module>
    dronepool.initialize()

^CTraceback (most recent call last):
  File "main.py", line 71, in <module>
    dronepool.initialize()
  File "/opt/DroneSym/dronesym-python/flask-api/src/dronepool.py", line 46, in initialize
    drones = node.get_drones()['drones']
  File "/opt/DroneSym/dronesym-python/flask-api/src/node.py", line 35, in get_drones
    return get_drones()
  File "/opt/DroneSym/dronesym-python/flask-api/src/node.py", line 35, in get_drones
    return get_drones()
  File "/opt/DroneSym/dronesym-python/flask-api/src/node.py", line 35, in get_drones
    return get_drones()
  File "/opt/DroneSym/dronesym-python/flask-api/src/node.py", line 34, in get_drones
    time.sleep(1)
KeyboardInterrupt
root@enC-ODM2:/opt/DroneSym/dronesym-python/flask-api/src#

**Comment by Benjamin-Mueggenburg** [comment]
Looking at this, did at any point to you press Ctrl + C or Ctrl + D? These are generally used as a keyboard interrupt, which is used to stop the program while it's running. For example in Python keyboard interrupts are used to break 'While True' loops.

**Comment by dilinade** [comment]
@tymiles003 Hi, I think the issue is with running the python script without running the node server.
Make sure that the node server is up and then try running python script.
