### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by mohak08** [scorelab/DroneSym#97]
EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.

**Comment by NewCodeKing** [comment]
@violentdelight we can work together, i just raised the same issue.
